server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # 根据微服务名称路由
#      routes:
#        - id: payment_routh
#          uri: lb://CLOUD-PAYMENT-SERVICE
#          predicates:
#            - Path=/payment/get/**
#        - id: payment_routh2
#          uri: lb://CLOUD-PAYMENT-SERVICE
#          predicates:
#            - Path=/payment/lb/**
#        - id: bilibili
#          uri: https://www.bilibili.com
#          predicates:
#            - Path=/video/BV1tJ41167Ai

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
