server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.42.128:1111 #配置Nacos地址
#        group: test

management:
  endpoints:
    web:
      exposure:
        include: '*'  #监控