server:
  port: 80
spring:
  application:
    name: order-feign-80-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
feign:
  client:
    config:
      default:
        #建立连接所用的时间，适用于网络状况正常的情况下，两端连接所需要的时间
        ConnectionTimeOut: 5000 # ms
        #指建立连接后从服务端读取到可用资源所用的时间
        ReadTimeOut: 5000
logging:
  level:
#    com.atguigu.springcloud.service: debug
    com.atguigu.springcloud.service.PaymentFeignService: debug  # 查看feign的调用情况
  file:
    path: ./logs
#  config: classpath:/logback.xml