server:
  port: 7003

spring:
  application:
    name: eureka-server-7003
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false  # 向eureka注册自己
    fetch-registry: false        # 拉取服务信息
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  server:
    enable-self-preservation: false #关闭自我保护机制，保证不可用服务被及时剔除
    eviction-interval-timer-in-ms: 2000